// use std::str::FromStr;
use crate::*;

grammar;

pub TestStatements: Vec<TestStatement> = {
    <s:TestStatement> => vec![s],
    <mut r:TestStatements> <s:TestStatement> => {
        r.push(s);
        r
    },
};

TestStatement: TestStatement = {
    "--" <c:TestComment> => TestStatement::Comment(c),
};

TestComment: TestComment = {
    "@type" <t:TestType> => TestComment::TypeAnnotation(t),
}

TestType: TestType = {
    "number" => TestType::Number,
    "string" => TestType::String,
}
